### ISSUE TITLE
funcfinder

### ISSUE THREAD

**Issue by alexmojaki** [billsix/methodfinder#1]
Not really an issue, just thought you might be interested to know about a similar project I made a while ago: https://github.com/alexmojaki/funcfinder

I think your idea is much more practical and useful.

**Comment by billsix** [comment]
Good stuff, thanks for sharing.

My project here is a rip-off of what I learned studying Smalltalk-80 (well, Squeak and Pharo).

Smalltalk's simple nature made the implementation of such a library more straightforward; i.e. my implementation has been very ad-hoc towards my own tests.  I'm trying to make this as useful as possible, towards libraries or packages of which I'm unaware, so please let me know if there are any deficiencies that I can remedy.
